name: newsuniverse
description: Your Gateway to the World's News a flutter web-view app.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  webview_flutter: ^4.4.1
  shared_preferences: ^2.2.2
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
#   - Assets for starter screen
    - assets/images/starter_icon/starter_icon.png
#   - Assets for bangla newspapers
    - assets/images/bangla_newspaper_images/prothom_alo.jpg
    - assets/images/bangla_newspaper_images/ittefaq.jpg
    - assets/images/bangla_newspaper_images/jugantor.jpg
    - assets/images/bangla_newspaper_images/kalerkantho.jpg
    - assets/images/bangla_newspaper_images/samakal.jpg
    - assets/images/bangla_newspaper_images/dailyjanakantha.jpg
    - assets/images/bangla_newspaper_images/bd_pratidin.jpg
    - assets/images/bangla_newspaper_images/nayadiganta.jpg
    - assets/images/bangla_newspaper_images/jjdin.jpg
    - assets/images/bangla_newspaper_images/amar_sangbad.jpg
    - assets/images/bangla_newspaper_images/protidinersangbad.jpg
    - assets/images/bangla_newspaper_images/dailysangram.jpg
    - assets/images/bangla_newspaper_images/mzamin.jpg
    - assets/images/bangla_newspaper_images/bonikbarta.jpg
    - assets/images/bangla_newspaper_images/bhorerkagoj.jpg
    - assets/images/bangla_newspaper_images/the_daily_inqilab.png
    - assets/images/bangla_newspaper_images/manobkantha.jpg
    - assets/images/bangla_newspaper_images/bdjournal.jpg
    - assets/images/bangla_newspaper_images/alokitobangladesh.jpg
    - assets/images/bangla_newspaper_images/sorejominbarta.jpg
    - assets/images/bangla_newspaper_images/shomoyeralo.jpg
    - assets/images/bangla_newspaper_images/kalbela.png
    - assets/images/bangla_newspaper_images/ajkalerkhobor.jpg
    - assets/images/bangla_newspaper_images/dainik_bangla.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
